/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationModule.JLayoutForms;

import ApplicationHelper.Helper;
import Authentication.AuthenticationSettings;
import BusinessModule.*;
import BusinessModule.OrderComparators.*;
import BusinessModule.OrderDetailsComparators.*;
import BusinessModule.StaffOrderComparators.*;
import BusinessModule.StockComporators.*;
import PresentationModule.BC_StationaryManagementSystem;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil
 */
public class JStaffModule extends javax.swing.JFrame
{

    private JPanel[] tabPanels;
    private boolean[] loadedTabs;
    private int totalTabs;

    private List<Order> approvedOrders = new ArrayList<>();
    private List<StaffOrder> pendingOrders = new ArrayList<>();
    private List<StationaryStock> stationaryStock = new ArrayList<>();
    private List<StationaryCategory> categories = new ArrayList<>();
    private boolean formLoad = false;

    public JStaffModule()
    {
        initComponents();

        LoadTab();
        LoadBoxCategory();
        formLoad = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        tpStaffControls = new javax.swing.JTabbedPane();
        pnlManageStaff = new javax.swing.JPanel();
        btnMyOrdersCloseTab = new javax.swing.JButton();
        tpMyOrderControls = new javax.swing.JTabbedPane();
        pnlMyOrders = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cmbSortOrder = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyOrders = new javax.swing.JTable();
        btnViewMySelectedOrder = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtMyOrderFilterID = new javax.swing.JTextField();
        cmdOrderViewByDate = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        pnlMyPendingOrders = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPendingOrders = new javax.swing.JTable();
        cmbSortOrderPending = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnViewMySelectedOrder1 = new javax.swing.JButton();
        txtMyOrderRequestFilter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmdMyOrderRequestViewByDate = new javax.swing.JComboBox<String>();
        pnlViewAllStock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAllStockStaff = new javax.swing.JTable();
        btnViewStationaryCloseTab = new javax.swing.JButton();
        btnAddFromStationary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtFilterProductName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbFilterCategory = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        cmbPrioritySort = new javax.swing.JComboBox<String>();
        jmbStaffModule = new javax.swing.JMenuBar();
        jmStaffAccount = new javax.swing.JMenu();
        jmStaffMyAccount = new javax.swing.JMenuItem();
        jmStaffLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmStaffModuleClose = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmStaffOrders = new javax.swing.JMenu();
        jmMyOrders = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmCurrentOrder = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmStaffStationary = new javax.swing.JMenu();
        jmStaffViewStationary = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMyOrdersCloseTab.setText("Close Tab");
        btnMyOrdersCloseTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMyOrdersCloseTabMouseClicked(evt);
            }
        });

        jLabel4.setText("Priority Order Sort:");

        cmbSortOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Order Total - Highest to Lowest", "Order Total - Lowest to Highest", "Order Date - Closest Date to Furthest Date", "Order Date - Furthest Date to Closest Date", "Approval Date - Closest Date to Furthest Date", "Approval Date - Furthest Date to Closest Date" }));
        cmbSortOrder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSortOrderItemStateChanged(evt);
            }
        });

        tblMyOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Stock Order ID", "Order Date", "Approval Date", "Order Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMyOrders);

        btnViewMySelectedOrder.setText("View Selected Order");
        btnViewMySelectedOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMySelectedOrderMouseClicked(evt);
            }
        });

        jLabel10.setText("Order ID:");

        txtMyOrderFilterID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMyOrderFilterIDKeyReleased(evt);
            }
        });

        cmdOrderViewByDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Yearly", "Monthly", "Daily" }));
        cmdOrderViewByDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmdOrderViewByDateItemStateChanged(evt);
            }
        });

        jLabel9.setText("View Orders By Date:");

        javax.swing.GroupLayout pnlMyOrdersLayout = new javax.swing.GroupLayout(pnlMyOrders);
        pnlMyOrders.setLayout(pnlMyOrdersLayout);
        pnlMyOrdersLayout.setHorizontalGroup(
            pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
                    .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtMyOrderFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyOrdersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewMySelectedOrder, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyOrdersLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cmdOrderViewByDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyOrdersLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(18, 18, 18)
                    .addComponent(cmbSortOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlMyOrdersLayout.setVerticalGroup(
            pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMyOrderFilterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdOrderViewByDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMySelectedOrder)
                .addContainerGap())
            .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMyOrdersLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlMyOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cmbSortOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(401, Short.MAX_VALUE)))
        );

        tpMyOrderControls.addTab("All My Orders", pnlMyOrders);

        tblPendingOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Order ID", "Order Date", "Order Total", "Order Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblPendingOrders);

        cmbSortOrderPending.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Order Total - Highest to Lowest", "Order Total - Lowest to Highest", "Order Date - Closest Date to Furthest Date", "Order Date - Furthest Date to Closest Date" }));
        cmbSortOrderPending.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSortOrderPendingItemStateChanged(evt);
            }
        });

        jLabel6.setText("Priority Order Sort:");

        btnViewMySelectedOrder1.setText("View Selected Order");
        btnViewMySelectedOrder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewMySelectedOrder1MouseClicked(evt);
            }
        });

        txtMyOrderRequestFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMyOrderRequestFilterKeyReleased(evt);
            }
        });

        jLabel11.setText("Stock Order ID:");

        jLabel12.setText("View Orders By Date:");

        cmdMyOrderRequestViewByDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Yearly", "Monthly", "Daily" }));
        cmdMyOrderRequestViewByDate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmdMyOrderRequestViewByDateItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlMyPendingOrdersLayout = new javax.swing.GroupLayout(pnlMyPendingOrders);
        pnlMyPendingOrders.setLayout(pnlMyPendingOrdersLayout);
        pnlMyPendingOrdersLayout.setHorizontalGroup(
            pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyPendingOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMyPendingOrdersLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtMyOrderRequestFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSortOrderPending, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMyPendingOrdersLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewMySelectedOrder1)
                            .addGroup(pnlMyPendingOrdersLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cmdMyOrderRequestViewByDate, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlMyPendingOrdersLayout.setVerticalGroup(
            pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMyPendingOrdersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSortOrderPending, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(txtMyOrderRequestFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMyPendingOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdMyOrderRequestViewByDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMySelectedOrder1)
                .addGap(60, 60, 60))
        );

        tpMyOrderControls.addTab("My Pending Orders", pnlMyPendingOrders);

        javax.swing.GroupLayout pnlManageStaffLayout = new javax.swing.GroupLayout(pnlManageStaff);
        pnlManageStaff.setLayout(pnlManageStaffLayout);
        pnlManageStaffLayout.setHorizontalGroup(
            pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpMyOrderControls)
                    .addGroup(pnlManageStaffLayout.createSequentialGroup()
                        .addComponent(btnMyOrdersCloseTab)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlManageStaffLayout.setVerticalGroup(
            pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMyOrderControls, javax.swing.GroupLayout.PREFERRED_SIZE, 459, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMyOrdersCloseTab)
                .addContainerGap())
        );

        tpStaffControls.addTab("Orders", pnlManageStaff);

        tblAllStockStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stationary Stock ID", "Product Name", "Category Name", "Model", "Price", "Quantity", "Date Of Entry / Update"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblAllStockStaff);

        btnViewStationaryCloseTab.setText("Close Tab");
        btnViewStationaryCloseTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewStationaryCloseTabMouseClicked(evt);
            }
        });

        btnAddFromStationary.setText("Add To Current Order");
        btnAddFromStationary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddFromStationaryMouseClicked(evt);
            }
        });

        jLabel1.setText("Product Name:");

        txtFilterProductName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterProductNameKeyReleased(evt);
            }
        });

        jLabel2.setText("Category Name:");

        cmbFilterCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilterCategoryItemStateChanged(evt);
            }
        });

        jLabel3.setText("Priority Sort:");

        cmbPrioritySort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Price - High to Low", "Price - Low to High", "Quantity - High to Low", "Quantity - Low to High", "Date - Closest Date to Furthest Date", "Date - Furthest Date to Closest Date" }));
        cmbPrioritySort.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPrioritySortItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlViewAllStockLayout = new javax.swing.GroupLayout(pnlViewAllStock);
        pnlViewAllStock.setLayout(pnlViewAllStockLayout);
        pnlViewAllStockLayout.setHorizontalGroup(
            pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                    .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                        .addComponent(btnViewStationaryCloseTab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddFromStationary))
                    .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                        .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(txtFilterProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbFilterCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPrioritySort, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlViewAllStockLayout.setVerticalGroup(
            pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilterProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPrioritySort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbFilterCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewStationaryCloseTab)
                    .addComponent(btnAddFromStationary))
                .addContainerGap())
        );

        tpStaffControls.addTab("View All Stationary", pnlViewAllStock);

        jmStaffAccount.setText("Account");

        jmStaffMyAccount.setText("My Account");
        jmStaffMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStaffMyAccountActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffMyAccount);

        jmStaffLogout.setText("Logout");
        jmStaffLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStaffLogoutActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffLogout);
        jmStaffAccount.add(jSeparator2);

        jmStaffModuleClose.setText("Close");
        jmStaffModuleClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStaffModuleCloseActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffModuleClose);
        jmStaffAccount.add(jSeparator1);

        jmbStaffModule.add(jmStaffAccount);

        jmStaffOrders.setText("Orders");

        jmMyOrders.setText("My Orders");
        jmMyOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMyOrdersActionPerformed(evt);
            }
        });
        jmStaffOrders.add(jmMyOrders);
        jmStaffOrders.add(jSeparator4);

        jmCurrentOrder.setText("View Current Order");
        jmCurrentOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCurrentOrderActionPerformed(evt);
            }
        });
        jmStaffOrders.add(jmCurrentOrder);
        jmStaffOrders.add(jSeparator3);

        jmbStaffModule.add(jmStaffOrders);

        jmStaffStationary.setText("Stationary");

        jmStaffViewStationary.setText("View Stationary");
        jmStaffViewStationary.setToolTipText("");
        jmStaffViewStationary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmStaffViewStationaryActionPerformed(evt);
            }
        });
        jmStaffStationary.add(jmStaffViewStationary);
        jmStaffStationary.add(jSeparator5);

        jmbStaffModule.add(jmStaffStationary);

        setJMenuBar(jmbStaffModule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpStaffControls)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpStaffControls)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Load Combo Boxes">
    private void LoadBoxCategory()
    {
        try
        {
            cmbFilterCategory.addItem("None");
            categories = new StationaryCategory().ReadStationaryCategory();

            for (StationaryCategory categoryData : categories)
            {
                cmbFilterCategory.addItem(categoryData.getName());
            }

            cmbFilterCategory.setSelectedIndex(0);
        } catch (NullPointerException npe)
        {
            Helper.DisplayError(npe.toString());
        }
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="LoadTab">
    private void LoadTab()
    {
        totalTabs = tpStaffControls.getComponentCount();
        tabPanels = new JPanel[totalTabs];
        loadedTabs = new boolean[totalTabs];
        try
        {
            for (int i = 0; i < totalTabs; i++)
            {
                JPanel singlePanel = ((JPanel) tpStaffControls.getComponent(0));
                tabPanels[i] = singlePanel;

                tpStaffControls.remove(0);
                loadedTabs[i] = false;
            }

        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Load Table Data">
    private void LoadTableUserOrderData()
    {
        approvedOrders = new Order().LoadMyApprovedOrders();
    }

    private void LoadTableAllStockData()
    {
        stationaryStock = new StationaryStock().LoadStationaryStock();
    }

    private void LoadMyPendingOrders()
    {
        pendingOrders = new StaffOrder().LoadMyPendingOrders();
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Populate Tables">
    private void PopulateUserOrdersTable()
    {
        try
        {
            DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();

            for (Order order : approvedOrders)
            {
                Object[] o = new Object[5];
                o[0] = order.getOrderID();
                o[1] = order.getStaffOrder().getStaffStockOrderID();
                o[2] = order.getStaffOrder().getOrderDate();
                o[3] = order.getApprovalDate();
                o[4] = order.getStaffOrder().getOrderTotal();
                model.addRow(o);
            }

            tblMyOrders.setModel(model);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }

    private void PopulateTableAllStock()
    {
        try
        {
            DefaultTableModel model = (DefaultTableModel) tblAllStockStaff.getModel();

            for (StationaryStock stockData : stationaryStock)
            {
                Object[] o = new Object[9];
                o[0] = stockData.getStationaryStockID();
                o[1] = stockData.getProductName();
                o[2] = new StationaryCategory().GetStationaryCategory(stockData.getStationaryCategoryID()).getName();
                o[3] = stockData.getModel();
                o[4] = stockData.getPrice();
                o[5] = stockData.getQuantity();
                o[6] = stockData.getDateOfEntryUpdate();
                model.addRow(o);
            }

            tblAllStockStaff.setModel(model);

            tblAllStockStaff.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblAllStockStaff.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblAllStockStaff.getColumnModel().getColumn(5).setPreferredWidth(30);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.getMessage());
        }
    }

    private void PopulateTablePendingOrders()
    {
        try
        {
            DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();

            for (StaffOrder staffOrder : pendingOrders)
            {
                Object[] o = new Object[4];
                o[0] = staffOrder.getStaffStockOrderID();
                o[1] = staffOrder.getOrderDate();
                o[2] = staffOrder.getOrderTotal();
                o[3] = staffOrder.getOrderStatus();
                model.addRow(o);
            }

            tblPendingOrders.setModel(model);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.getMessage());
        }
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Menu Buttons Press">
    private void jmStaffMyAccountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffMyAccountActionPerformed
    {//GEN-HEADEREND:event_jmStaffMyAccountActionPerformed
        try
        {
            this.setVisible(false);
            JUserAccount jua = new JUserAccount();
            jua.setVisible(true);
        } catch (NullPointerException npe)
        {
            Helper.DisplayError(npe.toString());
        }
    }//GEN-LAST:event_jmStaffMyAccountActionPerformed

    private void jmStaffLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffLogoutActionPerformed
    {//GEN-HEADEREND:event_jmStaffLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            dispose();
            AuthenticationSettings.setConnected(false);
            new Thread(new BC_StationaryManagementSystem()).start();
        }
    }//GEN-LAST:event_jmStaffLogoutActionPerformed

    private void jmStaffModuleCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffModuleCloseActionPerformed
    {//GEN-HEADEREND:event_jmStaffModuleCloseActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this application?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jmStaffModuleCloseActionPerformed

    private void jmMyOrdersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmMyOrdersActionPerformed
    {//GEN-HEADEREND:event_jmMyOrdersActionPerformed
        if (!loadedTabs[0])
        {
            try
            {
                if (!tpStaffControls.getSelectedComponent().equals(tabPanels[0]))
                {
                    tpStaffControls.addTab("Orders", tabPanels[0]);
                    tpStaffControls.setSelectedIndex(tpStaffControls.getComponentCount() - 1);
                    LoadTableUserOrderData();
                    PopulateUserOrdersTable();
                    LoadMyPendingOrders();
                    PopulateTablePendingOrders();
                    loadedTabs[0] = true;
                }
            } catch (NullPointerException npe)
            {
                tpStaffControls.addTab("Orders", tabPanels[0]);
                tpStaffControls.setSelectedIndex(tpStaffControls.getComponentCount() - 1);
                LoadTableUserOrderData();
                PopulateUserOrdersTable();
                LoadMyPendingOrders();
                PopulateTablePendingOrders();
                loadedTabs[0] = true;
            }
        }
    }//GEN-LAST:event_jmMyOrdersActionPerformed

    private void jmStaffViewStationaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffViewStationaryActionPerformed
    {//GEN-HEADEREND:event_jmStaffViewStationaryActionPerformed
        if (!loadedTabs[1])
        {
            try
            {
                if (!tpStaffControls.getSelectedComponent().equals(tabPanels[1]))
                {
                    tpStaffControls.addTab("View All Stationary", tabPanels[1]);
                    tpStaffControls.setSelectedIndex(tpStaffControls.getComponentCount() - 1);
                    LoadTableAllStockData();
                    PopulateTableAllStock();
                    loadedTabs[1] = true;
                }
            } catch (NullPointerException npe)
            {
                tpStaffControls.addTab("View All Stationary", tabPanels[1]);
                tpStaffControls.setSelectedIndex(tpStaffControls.getComponentCount() - 1);
                LoadTableAllStockData();
                PopulateTableAllStock();
                loadedTabs[1] = true;
            }
        }
    }//GEN-LAST:event_jmStaffViewStationaryActionPerformed

    private void jmCurrentOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmCurrentOrderActionPerformed
    {//GEN-HEADEREND:event_jmCurrentOrderActionPerformed
        try
        {
            if (!Authentication.ActiveAccess.getCurrentOrderList().isEmpty())
            {
                OrderDialog od = new OrderDialog(null, true);
                od.setVisible(true);           
            } else
            {
                Helper.DisplayError("There is no current order yet, please add some stationary stock to create one.", "No Existing Order");
            }
        }
        catch (NullPointerException npe)
        {
            Helper.DisplayError("There is no current order yet, please add some stationary stock to create one.", "No Existing Order");
        }
    }//GEN-LAST:event_jmCurrentOrderActionPerformed

    private void cmbPrioritySortItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbPrioritySortItemStateChanged
    {//GEN-HEADEREND:event_cmbPrioritySortItemStateChanged
        switch (cmbPrioritySort.getSelectedIndex())
        {
            case 0:
            Collections.sort(stationaryStock, new StockID());
            break;
            case 1:
            Collections.sort(stationaryStock, new StockPrice_HighToLow());
            break;

            case 2:
            Collections.sort(stationaryStock, new StockPrice_LowToHigh());
            break;

            case 3:
            Collections.sort(stationaryStock, new StockQuantity_HighToLow());
            break;

            case 4:
            Collections.sort(stationaryStock, new StockQuantity_LowToHigh());
            break;

            case 5:
            Collections.sort(stationaryStock, new StockDate_ClosestToFurthest());
            break;

            case 6:
            Collections.sort(stationaryStock, new StockDate_FurthestToClosest());
            break;
        }

        DefaultTableModel model = (DefaultTableModel) tblAllStockStaff.getModel();
        model.setRowCount(0);
        PopulateTableAllStock();
    }//GEN-LAST:event_cmbPrioritySortItemStateChanged

    private void cmbFilterCategoryItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbFilterCategoryItemStateChanged
    {//GEN-HEADEREND:event_cmbFilterCategoryItemStateChanged
        if (formLoad)
        {
            try
            {
                LoadTableAllStockData();
                List<StationaryStock> stockToRemove = new ArrayList<>();

                for (StationaryStock stock : stationaryStock)
                {
                    for (StationaryCategory category : categories)
                    {
                        if (category.getName().equalsIgnoreCase(cmbFilterCategory.getSelectedItem().toString()))
                        {
                            if (stock.getStationaryCategoryID() != category.getStationaryCategoryID())
                            {
                                stockToRemove.add(stock);
                            }
                        }
                    }
                }

                stationaryStock.removeAll(stockToRemove);

                DefaultTableModel model = (DefaultTableModel) tblAllStockStaff.getModel();
                model.setRowCount(0);
                PopulateTableAllStock();

                if (stationaryStock.size() <= 0)
                {
                    Helper.DisplayError("There are no categories located in requested filter", "Filter Information");
                }
            } catch (Exception ex)
            {
                if (ex instanceof NullPointerException)
                {
                    LoadTableAllStockData();
                    PopulateTableAllStock();
                } else
                {
                    Helper.DisplayError(ex.toString(), "Error In Filter");
                }
            }
        }
    }//GEN-LAST:event_cmbFilterCategoryItemStateChanged

    private void txtFilterProductNameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtFilterProductNameKeyReleased
    {//GEN-HEADEREND:event_txtFilterProductNameKeyReleased
        try
        {
            LoadTableAllStockData();
            List<StationaryStock> stockToRemove = new ArrayList<>();

            for (StationaryStock stock : stationaryStock)
            {
                if (!stock.getProductName().toUpperCase().contains(txtFilterProductName.getText().toUpperCase()))
                {
                    stockToRemove.add(stock);
                }
            }

            stationaryStock.removeAll(stockToRemove);

            DefaultTableModel model = (DefaultTableModel) tblAllStockStaff.getModel();
            model.setRowCount(0);
            PopulateTableAllStock();

            if (stationaryStock.size() <= 0)
            {
                throw new FilterException("There are no products that match that filter");
            }
        } catch (FilterException fe)
        {
            Helper.DisplayError(fe.toString(), "Filter Exception");
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString(), "Error In Filter");
        }
    }//GEN-LAST:event_txtFilterProductNameKeyReleased

    private void btnAddFromStationaryMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAddFromStationaryMouseClicked
    {//GEN-HEADEREND:event_btnAddFromStationaryMouseClicked
        try
        {
            int stationaryStockID = Integer.parseInt(tblAllStockStaff.getValueAt(tblAllStockStaff.getSelectedRow(), 0).toString());
            int quantity = Integer.parseInt(JOptionPane.showInputDialog("Please enter a quantity amount you would like to request: "));
            double price = Double.parseDouble(tblAllStockStaff.getValueAt(tblAllStockStaff.getSelectedRow(), 4).toString());

            if (quantity < 1)
            {
                throw new NumberFormatException();
            }

            StaffStockOrder selectedStockEntry = new StaffStockOrder(stationaryStockID, quantity, price);
            List<StaffStockOrder> orderToRemove = new ArrayList<>();

            for (StaffStockOrder checkDup : Authentication.ActiveAccess.CurrentOrderList)
            {
                if (checkDup.getStationaryStockID() == selectedStockEntry.getStationaryStockID())
                {
                    orderToRemove.add(checkDup);
                    selectedStockEntry.setQuantity(selectedStockEntry.getQuantity() + checkDup.getQuantity());
                }
            }

            Authentication.ActiveAccess.CurrentOrderList.removeAll(orderToRemove);
            Authentication.ActiveAccess.CurrentOrderList.add(selectedStockEntry);
            Helper.DisplayError("Succesfully added to current order.", "Succesfully added");
        } catch (NumberFormatException nfe)
        {
            Helper.DisplayError("Please enter a correct quantity value", "Invalid Type Entered");
        }
    }//GEN-LAST:event_btnAddFromStationaryMouseClicked

    private void btnViewStationaryCloseTabMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnViewStationaryCloseTabMouseClicked
    {//GEN-HEADEREND:event_btnViewStationaryCloseTabMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblAllStockStaff.getModel();
        model.setRowCount(0);
        tpStaffControls.remove(tabPanels[1]);
        loadedTabs[1] = false;
    }//GEN-LAST:event_btnViewStationaryCloseTabMouseClicked

    private void cmbSortOrderItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbSortOrderItemStateChanged
    {//GEN-HEADEREND:event_cmbSortOrderItemStateChanged
        switch (cmbSortOrder.getSelectedIndex())
        {
            case 0:
                Collections.sort(approvedOrders, new OrderID());
                break;
            case 1:
            Collections.sort(approvedOrders, new OrderTotal_HighestToLowest());
            break;

            case 2:
            Collections.sort(approvedOrders, new OrderTotal_LowestToHighest());
            break;

            case 3:
            Collections.sort(approvedOrders, new OrderDate_ClosestToFurthest());
            break;

            case 4:
            Collections.sort(approvedOrders, new OrderDate_FurthestToClosest());
            break;

            case 5:
            Collections.sort(approvedOrders, new OrderApprovalDate_ClosestToFurthest());
            break;

            case 6:
            Collections.sort(approvedOrders, new OrderApprovalDate_FurthestToClosest());
            break;
        }

        DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();
        model.setRowCount(0);
        PopulateUserOrdersTable();
    }//GEN-LAST:event_cmbSortOrderItemStateChanged

    private void btnMyOrdersCloseTabMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnMyOrdersCloseTabMouseClicked
    {//GEN-HEADEREND:event_btnMyOrdersCloseTabMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();
        model.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) tblPendingOrders.getModel();
        model2.setRowCount(0);
        tpStaffControls.remove(tabPanels[0]);
        loadedTabs[0] = false;
    }//GEN-LAST:event_btnMyOrdersCloseTabMouseClicked

    private void cmbSortOrderPendingItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbSortOrderPendingItemStateChanged
    {//GEN-HEADEREND:event_cmbSortOrderPendingItemStateChanged
        switch (cmbSortOrderPending.getSelectedIndex())
        {
            case 0:
            Collections.sort(pendingOrders, new StaffOrderID());
                break;
            case 1:
            Collections.sort(pendingOrders, new StaffOrderTotal_HighestToLowest());
            break;

            case 2:
            Collections.sort(pendingOrders, new StaffOrderTotal_LowestToHighest());
            break;

            case 3:
            Collections.sort(pendingOrders, new StaffOrderDate_ClosestToFurthest());
            break;

            case 4:
            Collections.sort(pendingOrders, new StaffOrderDate_FurthestToClosest());
            break;
        }

        DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();
        model.setRowCount(0);
        PopulateTablePendingOrders();
    }//GEN-LAST:event_cmbSortOrderPendingItemStateChanged

    private void btnViewMySelectedOrderMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnViewMySelectedOrderMouseClicked
    {//GEN-HEADEREND:event_btnViewMySelectedOrderMouseClicked
        try
        {
            String stockOrderID = tblMyOrders.getValueAt(tblMyOrders.getSelectedRow(), 1).toString();
            String orderID = tblMyOrders.getValueAt(tblMyOrders.getSelectedRow(), 0).toString();
            Date approvalDate = (Date)tblMyOrders.getValueAt(tblMyOrders.getSelectedRow(), 3);
            Date orderDate = (Date)tblMyOrders.getValueAt(tblMyOrders.getSelectedRow(), 2);
            double orderTotal = (Double)tblMyOrders.getValueAt(tblMyOrders.getSelectedRow(), 4);

            Authentication.ActiveAccess.CurrentOrder = new CurrentOrder();
            Authentication.ActiveAccess.CurrentOrder.setOrderID(orderID);
            Authentication.ActiveAccess.CurrentOrder.setApprovalDate(approvalDate);
            Authentication.ActiveAccess.CurrentOrder.setTotalPrice(orderTotal);
            Authentication.ActiveAccess.CurrentOrder.setCurrentDate(orderDate);
            Authentication.ActiveAccess.CurrentOrder.setStaffUsername(AuthenticationSettings.getConnectedStaff().getStaffUsername());
            Authentication.ActiveAccess.CurrentOrder.setStaffStockID(stockOrderID);
            Authentication.ActiveAccess.CurrentOrder.setViewOrder(true);

            SelectOrder(stockOrderID);
        }
        catch (ArrayIndexOutOfBoundsException ex)
        {
            Helper.DisplayError("Please ensure you select a table entry before performing this action", "Error in order selection");
        }
        catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }

    }//GEN-LAST:event_btnViewMySelectedOrderMouseClicked

    private void btnViewMySelectedOrder1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnViewMySelectedOrder1MouseClicked
    {//GEN-HEADEREND:event_btnViewMySelectedOrder1MouseClicked
        try
        {      
            String stockOrderID = tblPendingOrders.getValueAt(tblPendingOrders.getSelectedRow(), 0).toString();
            Date orderDate = (Date)tblPendingOrders.getValueAt(tblPendingOrders.getSelectedRow(), 1);
            double orderTotal = (Double)tblPendingOrders.getValueAt(tblPendingOrders.getSelectedRow(), 2);
            
            Authentication.ActiveAccess.CurrentOrder = new CurrentOrder();

            Authentication.ActiveAccess.CurrentOrder.setTotalPrice(orderTotal);
            Authentication.ActiveAccess.CurrentOrder.setCurrentDate(orderDate);
            Authentication.ActiveAccess.CurrentOrder.setStaffUsername(AuthenticationSettings.getConnectedStaff().getStaffUsername());
            Authentication.ActiveAccess.CurrentOrder.setStaffStockID(stockOrderID);
            Authentication.ActiveAccess.CurrentOrder.setViewStaffPending(true);
            
            SelectOrder(stockOrderID);
        }
        catch (ArrayIndexOutOfBoundsException ex)
        {
            Helper.DisplayError("Please ensure you select a table entry before performing this action", "Error in order selection");
        }
        catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }//GEN-LAST:event_btnViewMySelectedOrder1MouseClicked

    private void txtMyOrderFilterIDKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtMyOrderFilterIDKeyReleased
    {//GEN-HEADEREND:event_txtMyOrderFilterIDKeyReleased
        try
        {
            LoadTableUserOrderData();
            List<Order> orderToRemove = new ArrayList<>();

            for (Order order : approvedOrders)
            {
                if(!order.getOrderID().toUpperCase().contains(txtMyOrderFilterID.getText().toUpperCase()))
                {
                    orderToRemove.add(order);
                }
            }

            approvedOrders.removeAll(orderToRemove);

            DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();
            model.setRowCount(0);
            PopulateUserOrdersTable();

            if (approvedOrders.size() <= 0)
            {
                throw new FilterException("There are no orders that match that filter");
            }
        }
        catch (FilterException fe)
        {
            Helper.DisplayError(fe.getMessage(), "Filter Exception");
        }
        catch (Exception ex)
        {
            Helper.DisplayError(ex.toString(), "Error In Filter");
        }
    }//GEN-LAST:event_txtMyOrderFilterIDKeyReleased

    private void cmdOrderViewByDateItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmdOrderViewByDateItemStateChanged
    {//GEN-HEADEREND:event_cmdOrderViewByDateItemStateChanged
        List<Order> toRemove = new ArrayList<>();
        Calendar cal1 = Calendar.getInstance();
        Calendar cal2 = Calendar.getInstance();
        LoadTableUserOrderData();

        switch(cmdOrderViewByDate.getSelectedIndex())
        {        
            case 1:
                for (Order order : approvedOrders)
                {
                    cal1.setTime(order.getApprovalDate());
                    cal2.setTime(new Date());
                    
                    boolean sameYear = cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR);
                    if(!sameYear)
                    {
                        toRemove.add(order);
                    }
                }
                break;
                
            case 2:
                for (Order order : approvedOrders)
                {
                    cal1.setTime(order.getApprovalDate());
                    cal2.setTime(new Date());
                    
                    boolean sameMonth = ((cal1.get(Calendar.MONTH) == cal2.get(Calendar.MONTH)) && (cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR)));
                    if(!sameMonth)
                    {
                        toRemove.add(order);
                    }
                }
                break;
                
            case 3:
                for (Order order : approvedOrders)
                {
                    cal1.setTime(order.getApprovalDate());
                    cal2.setTime(new Date());
                    
                    boolean sameDay = cal1.get(Calendar.DAY_OF_YEAR) == cal2.get(Calendar.DAY_OF_YEAR);
                    if(!sameDay)
                    {
                        toRemove.add(order);
                    }
                }
                break;
        }

        approvedOrders.removeAll(toRemove);

        DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();
        model.setRowCount(0);
        PopulateUserOrdersTable();
    }//GEN-LAST:event_cmdOrderViewByDateItemStateChanged

    private void txtMyOrderRequestFilterKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtMyOrderRequestFilterKeyReleased
    {//GEN-HEADEREND:event_txtMyOrderRequestFilterKeyReleased
        try
        {
            LoadMyPendingOrders();
            List<StaffOrder> pendingOrderToRemove = new ArrayList<>();

            for (StaffOrder staffOrder : pendingOrders)
            {
                if(!staffOrder.getStaffStockOrderID().toUpperCase().contains(txtMyOrderRequestFilter.getText().toUpperCase()))
                {
                    pendingOrderToRemove.add(staffOrder);
                }
            }

            pendingOrders.removeAll(pendingOrderToRemove);

            DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();
            model.setRowCount(0);
            PopulateTablePendingOrders();

            if (pendingOrders.size() <= 0)
            {
                throw new FilterException("There are no orders that match that filter");
            }
        }
        catch (FilterException fe)
        {
            Helper.DisplayError(fe.getMessage(), "Filter Exception");
        }
        catch (Exception ex)
        {
            Helper.DisplayError(ex.toString(), "Error In Filter");
        }
    }//GEN-LAST:event_txtMyOrderRequestFilterKeyReleased

    private void cmdMyOrderRequestViewByDateItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmdMyOrderRequestViewByDateItemStateChanged
    {//GEN-HEADEREND:event_cmdMyOrderRequestViewByDateItemStateChanged
        List<StaffOrder> toRemove = new ArrayList<>();
        Calendar cal1 = Calendar.getInstance();
        Calendar cal2 = Calendar.getInstance();
        LoadMyPendingOrders();

        switch(cmdMyOrderRequestViewByDate.getSelectedIndex())
        {
            case 1:
            for (StaffOrder pendingOrder : pendingOrders)
            {
                cal1.setTime(pendingOrder.getOrderDate());
                cal2.setTime(new Date());

                boolean sameYear = cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR);
                if(!sameYear)
                {
                    toRemove.add(pendingOrder);
                }
            }
            break;

            case 2:
            for (StaffOrder pendingOrder : pendingOrders)
            {
                cal1.setTime(pendingOrder.getOrderDate());
                cal2.setTime(new Date());

                boolean sameMonth = ((cal1.get(Calendar.MONTH) == cal2.get(Calendar.MONTH)) && (cal1.get(Calendar.YEAR) == cal2.get(Calendar.YEAR)));
                if(!sameMonth)
                {
                    toRemove.add(pendingOrder);
                }
            }
            break;

            case 3:
            for (StaffOrder pendingOrder : pendingOrders)
            {
                cal1.setTime(pendingOrder.getOrderDate());
                cal2.setTime(new Date());

                boolean sameDay = cal1.get(Calendar.DAY_OF_YEAR) == cal2.get(Calendar.DAY_OF_YEAR);
                if(!sameDay)
                {
                    toRemove.add(pendingOrder);
                }
            }
            break;
        }

        pendingOrders.removeAll(toRemove);

        DefaultTableModel model = (DefaultTableModel) tblPendingOrders.getModel();
        model.setRowCount(0);
        PopulateTablePendingOrders();
    }//GEN-LAST:event_cmdMyOrderRequestViewByDateItemStateChanged

    private void SelectOrder(String stockOrderID)
    {
        Authentication.ActiveAccess.CurrentOrder.setOrderStock(new StaffStockOrder().GetOrderDetails(stockOrderID));
        Authentication.ActiveAccess.CurrentOrderList = Authentication.ActiveAccess.CurrentOrder.getOrderStock();
        OrderDialog od = new OrderDialog(null, true);
        od.setVisible(true);
        
        Authentication.ActiveAccess.CurrentOrder = null;
        Authentication.ActiveAccess.CurrentOrderList = null;
        
        DefaultTableModel model = (DefaultTableModel) tblMyOrders.getModel();
        model.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) tblPendingOrders.getModel();
        model2.setRowCount(0);
        
        LoadTableUserOrderData();
        LoadMyPendingOrders();
        PopulateUserOrdersTable();
        PopulateTablePendingOrders();
    }
    
//</editor-fold>
    /**
     * @param args the command line arguments
     */
    public void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new JStaffModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFromStationary;
    private javax.swing.JButton btnMyOrdersCloseTab;
    private javax.swing.JButton btnViewMySelectedOrder;
    private javax.swing.JButton btnViewMySelectedOrder1;
    private javax.swing.JButton btnViewStationaryCloseTab;
    private javax.swing.JComboBox<String> cmbFilterCategory;
    private javax.swing.JComboBox<String> cmbPrioritySort;
    private javax.swing.JComboBox cmbSortOrder;
    private javax.swing.JComboBox cmbSortOrderPending;
    private javax.swing.JComboBox<String> cmdMyOrderRequestViewByDate;
    private javax.swing.JComboBox<String> cmdOrderViewByDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem jmCurrentOrder;
    private javax.swing.JMenuItem jmMyOrders;
    private javax.swing.JMenu jmStaffAccount;
    private javax.swing.JMenuItem jmStaffLogout;
    private javax.swing.JMenuItem jmStaffModuleClose;
    private javax.swing.JMenuItem jmStaffMyAccount;
    private javax.swing.JMenu jmStaffOrders;
    private javax.swing.JMenu jmStaffStationary;
    private javax.swing.JMenuItem jmStaffViewStationary;
    private javax.swing.JMenuBar jmbStaffModule;
    private javax.swing.JPanel pnlManageStaff;
    private javax.swing.JPanel pnlMyOrders;
    private javax.swing.JPanel pnlMyPendingOrders;
    private javax.swing.JPanel pnlViewAllStock;
    private javax.swing.JTable tblAllStockStaff;
    private javax.swing.JTable tblMyOrders;
    private javax.swing.JTable tblPendingOrders;
    private javax.swing.JTabbedPane tpMyOrderControls;
    private javax.swing.JTabbedPane tpStaffControls;
    private javax.swing.JTextField txtFilterProductName;
    private javax.swing.JTextField txtMyOrderFilterID;
    private javax.swing.JTextField txtMyOrderRequestFilter;
    // End of variables declaration//GEN-END:variables
}
