/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationModule.JLayoutForms;

import ApplicationHelper.Helper;
import Authentication.AuthenticationSettings;
import BusinessModule.Campus;
import BusinessModule.Department;
import BusinessModule.Staff;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Neil
 */
public class JUserAccount extends javax.swing.JFrame
{

    protected List<Campus> staffCampus = new ArrayList<>();
    protected List<Department> staffDepartment = new ArrayList<>();

    public JUserAccount()
    {
        initComponents();
        LoadBoxes();
        ResetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtStaffName = new javax.swing.JTextField();
        txtStaffSurname = new javax.swing.JTextField();
        cmbStaffCampus = new javax.swing.JComboBox<>();
        cmbStaffDepartment = new javax.swing.JComboBox<>();
        txtStaffCellNo = new javax.swing.JTextField();
        txtStaffEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStaffUsername = new javax.swing.JTextField();
        txtStaffPassword = new javax.swing.JPasswordField();
        txtStaffConfirmPassword = new javax.swing.JPasswordField();
        btnStaffBack = new javax.swing.JButton();
        btnStaffUpdate = new javax.swing.JButton();
        btnStaffClose = new javax.swing.JButton();
        btnAccountClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Campus:");

        jLabel4.setText("Department:");

        jLabel5.setText("Cell No:");

        jLabel6.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStaffSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbStaffCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(cmbStaffDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStaffCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStaffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStaffSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbStaffCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbStaffDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStaffCellNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStaffEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Security Information"));

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        jLabel9.setText("Confirm Password:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStaffConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtStaffPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtStaffUsername)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtStaffUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtStaffConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStaffBack.setText("Back");
        btnStaffBack.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnStaffBackMouseClicked(evt);
            }
        });

        btnStaffUpdate.setText("Update");
        btnStaffUpdate.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnStaffUpdateMouseClicked(evt);
            }
        });

        btnStaffClose.setText("Close");
        btnStaffClose.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnStaffCloseMouseClicked(evt);
            }
        });

        btnAccountClear.setText("Clear");
        btnAccountClear.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAccountClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStaffBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccountClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(btnStaffClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaffUpdate)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStaffBack)
                        .addComponent(btnAccountClear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnStaffClose)
                        .addComponent(btnStaffUpdate)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(83, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffBackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnStaffBackMouseClicked
    {//GEN-HEADEREND:event_btnStaffBackMouseClicked
        this.setVisible(false);
        JStaffModule jsm = new JStaffModule();
        jsm.setVisible(true);
    }//GEN-LAST:event_btnStaffBackMouseClicked

    private void btnStaffUpdateMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnStaffUpdateMouseClicked
    {//GEN-HEADEREND:event_btnStaffUpdateMouseClicked
        boolean validInput = false;
        String name, surname, campus, department, cellNo, email, username, password, confirmPassword;

        name = txtStaffName.getText();
        surname = txtStaffSurname.getText();
        campus = cmbStaffCampus.getSelectedItem().toString();
        department = cmbStaffDepartment.getSelectedItem().toString();
        cellNo = txtStaffCellNo.getText();
        email = txtStaffEmail.getText();
        username = txtStaffUsername.getText();
        password = String.valueOf(txtStaffPassword.getPassword());
        confirmPassword = String.valueOf(txtStaffConfirmPassword.getPassword());

        try
        {
            Validation val = new Validation();
            validInput = val.ValidateStaffAccountInput(name, surname, campus, department, cellNo, email, username, password, confirmPassword);
            int campusID = 0;
            int deptID = 0;

            if (validInput)
            {
                for (Campus campusData : staffCampus)
                {
                    if (campusData.getCampusName().equals(campus))
                    {
                        campusID = campusData.getCampusID();
                    }
                }

                for (Department departmentData : staffDepartment)
                {
                    if (departmentData.getDepartmentName().equals(department))
                    {
                        deptID = departmentData.getDepartmentID();
                    }
                }
                if (campusID != 0 && deptID != 0)
                {
                    Staff staff = null;
                    if(password.length() == 0)
                    {
                        staff = new Staff(AuthenticationSettings.getConnectedStaff().getStaffID(), name, surname, campusID, deptID, cellNo, email, username, AuthenticationSettings.getConnectedStaff().getStaffPassword());
                    }
                    else
                    {
                        staff = new Staff(AuthenticationSettings.getConnectedStaff().getStaffID(), name, surname, campusID, deptID, cellNo, email, username, password);
                        staff.setStaffPassword(staff.getHashPassword());
                    }
                    staff.UpdateStaffEntry();
                    JOptionPane.showConfirmDialog(this, "Succesfully updated your account", "Update Succesful", JOptionPane.DEFAULT_OPTION);
                    AuthenticationSettings.setConnectedStaff(staff);

                    this.setVisible(false);
                    JStaffModule jsm = new JStaffModule();
                    jsm.setVisible(true);
                } else
                {
                    throw new Exception("Error in ID set for field!");
                }
            } else
            {
                ResetForm();
            }
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }//GEN-LAST:event_btnStaffUpdateMouseClicked

    private void ResetForm()
    {
        txtStaffName.setText(AuthenticationSettings.getConnectedStaff().getStaffName());
        txtStaffSurname.setText(AuthenticationSettings.getConnectedStaff().getStaffSurname());
        cmbStaffCampus.setSelectedIndex(staffCampus.indexOf(AuthenticationSettings.getConnectedStaff().getStaffID()));
        cmbStaffDepartment.setSelectedIndex(staffDepartment.indexOf(AuthenticationSettings.getConnectedStaff().getStaffDepartment()));
        txtStaffEmail.setText(AuthenticationSettings.getConnectedStaff().getStaffEmail());
        txtStaffCellNo.setText(AuthenticationSettings.getConnectedStaff().getStaffCellNo());

        txtStaffUsername.setText(AuthenticationSettings.getConnectedStaff().getStaffUsername());
        txtStaffPassword.setText("");
        txtStaffConfirmPassword.setText("");

        for (Campus campusData : staffCampus)
        {
            if (campusData.getCampusID() == AuthenticationSettings.getConnectedStaff().getStaffCampusID())
            {
                cmbStaffCampus.setSelectedItem(campusData.getCampusName());
            }
        }

        for (Department departmentData : staffDepartment)
        {
            if (departmentData.getDepartmentID() == AuthenticationSettings.getConnectedStaff().getStaffDepartment())
            {
                cmbStaffDepartment.setSelectedItem(departmentData.getDepartmentName());
            }
        }
    }

    private void btnStaffCloseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnStaffCloseMouseClicked
    {//GEN-HEADEREND:event_btnStaffCloseMouseClicked
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this application?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnStaffCloseMouseClicked

    private void btnAccountClearMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAccountClearMouseClicked
    {//GEN-HEADEREND:event_btnAccountClearMouseClicked
        ResetForm();
    }//GEN-LAST:event_btnAccountClearMouseClicked

    private void LoadBoxes()
    {
        Campus campus = new Campus();
        Department department = new Department();

        staffCampus = campus.ReadCampus();
        staffDepartment = department.ReadDepartment();

        for (Campus campusData : staffCampus)
        {
            cmbStaffCampus.addItem(campusData.getCampusName());
        }

        for (Department departmentData : staffDepartment)
        {
            cmbStaffDepartment.addItem(departmentData.getDepartmentName());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JUserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JUserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountClear;
    private javax.swing.JButton btnStaffBack;
    private javax.swing.JButton btnStaffClose;
    private javax.swing.JButton btnStaffUpdate;
    private javax.swing.JComboBox<String> cmbStaffCampus;
    private javax.swing.JComboBox<String> cmbStaffDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtStaffCellNo;
    private javax.swing.JPasswordField txtStaffConfirmPassword;
    private javax.swing.JTextField txtStaffEmail;
    private javax.swing.JTextField txtStaffName;
    private javax.swing.JPasswordField txtStaffPassword;
    private javax.swing.JTextField txtStaffSurname;
    private javax.swing.JTextField txtStaffUsername;
    // End of variables declaration//GEN-END:variables
}
