/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationModule.JLayourForms;

import ApplicationHelper.Helper;
import BusinessModule.Campus;
import BusinessModule.Department;
import BusinessModule.Staff;
import BusinessModule.StationaryCategory;
import BusinessModule.StationaryStock;
import PresentationModule.BC_StationaryManagementSystem;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neil
 */
public class JAdminModule extends javax.swing.JFrame
{

    private Staff selectedStaff;
    private StationaryStock selectedStock;
    private List<Staff> registerStaff = new ArrayList<>();
    private List<Staff> users = new ArrayList<>();
    private List<StationaryStock> stationaryStock = new ArrayList<>();
    private JPanel[] tabPanels;
    private int totalTabs;

    /**
     * Creates new form AdminModule
     */
    public JAdminModule()
    {
        initComponents();

        LoadTab();   
    }

    private void LoadTab()
    {
        totalTabs = tpAdminControls.getComponentCount();
        tabPanels = new JPanel[totalTabs];
        try
        {
            for (int i = 0; i < totalTabs; i++)
            {
                JPanel singlePanel = ((JPanel) tpAdminControls.getComponent(0));
                tabPanels[i] = singlePanel;

                tpAdminControls.remove(0);
            }

        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpAdminControls = new javax.swing.JTabbedPane();
        pnlManageStaff = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewUsers = new javax.swing.JTable();
        btnViewUsersBack = new javax.swing.JButton();
        pnlUserRegistrationRequests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegisterRequests = new javax.swing.JTable();
        btnRegisterUserBack = new javax.swing.JButton();
        btnDeleteRegisterUser = new javax.swing.JButton();
        btnAcceptUser = new javax.swing.JButton();
        pnlViewAllStock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAllStock = new javax.swing.JTable();
        btnViewAllStockBack = new javax.swing.JButton();
        btnPromptUpdate = new javax.swing.JButton();
        btnDeleteStock = new javax.swing.JButton();
        jmbAdminModule = new javax.swing.JMenuBar();
        jmAdminApplication = new javax.swing.JMenu();
        jmAdminLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmAdminClose = new javax.swing.JMenuItem();
        jmAccounts = new javax.swing.JMenu();
        jmManageRegisteredUsers = new javax.swing.JMenuItem();
        jmViewRegistrationRequests = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmManageStocks = new javax.swing.JMenu();
        jmManageAllStock = new javax.swing.JMenuItem();
        jmInserStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblViewUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Name", "Surname", "Campus Name", "Department Name", "Cell No", "Email", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewUsers.setName(""); // NOI18N
        jScrollPane2.setViewportView(tblViewUsers);

        btnViewUsersBack.setText("Back");
        btnViewUsersBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewUsersBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlManageStaffLayout = new javax.swing.GroupLayout(pnlManageStaff);
        pnlManageStaff.setLayout(pnlManageStaffLayout);
        pnlManageStaffLayout.setHorizontalGroup(
            pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlManageStaffLayout.createSequentialGroup()
                        .addComponent(btnViewUsersBack)
                        .addGap(946, 946, 946)))
                .addContainerGap())
        );
        pnlManageStaffLayout.setVerticalGroup(
            pnlManageStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnViewUsersBack)
                .addContainerGap())
        );

        tpAdminControls.addTab("Manage Staff", pnlManageStaff);

        tblRegisterRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Name", "Surname", "Campus Name", "Department Name", "Cell No", "Email", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRegisterRequests.setName(""); // NOI18N
        jScrollPane1.setViewportView(tblRegisterRequests);

        btnRegisterUserBack.setText("Back");
        btnRegisterUserBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterUserBackMouseClicked(evt);
            }
        });

        btnDeleteRegisterUser.setText("Delete User");
        btnDeleteRegisterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteRegisterUserMouseClicked(evt);
            }
        });

        btnAcceptUser.setText("Accept User");
        btnAcceptUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceptUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlUserRegistrationRequestsLayout = new javax.swing.GroupLayout(pnlUserRegistrationRequests);
        pnlUserRegistrationRequests.setLayout(pnlUserRegistrationRequestsLayout);
        pnlUserRegistrationRequestsLayout.setHorizontalGroup(
            pnlUserRegistrationRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserRegistrationRequestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUserRegistrationRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(pnlUserRegistrationRequestsLayout.createSequentialGroup()
                        .addComponent(btnRegisterUserBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteRegisterUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcceptUser)))
                .addContainerGap())
        );
        pnlUserRegistrationRequestsLayout.setVerticalGroup(
            pnlUserRegistrationRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserRegistrationRequestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(pnlUserRegistrationRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterUserBack)
                    .addComponent(btnAcceptUser)
                    .addComponent(btnDeleteRegisterUser))
                .addContainerGap())
        );

        tpAdminControls.addTab("User Registration Requests", pnlUserRegistrationRequests);
        pnlUserRegistrationRequests.getAccessibleContext().setAccessibleName("");

        tblAllStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stationary Stock ID", "Product Name", "Category Name", "Model", "Price", "Quantity", "Date Of Entry / Update"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblAllStock);

        btnViewAllStockBack.setLabel("Back");
        btnViewAllStockBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewAllStockBackMouseClicked(evt);
            }
        });

        btnPromptUpdate.setText("Update");
        btnPromptUpdate.setToolTipText("");
        btnPromptUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPromptUpdateMouseClicked(evt);
            }
        });

        btnDeleteStock.setText("Delete");
        btnDeleteStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlViewAllStockLayout = new javax.swing.GroupLayout(pnlViewAllStock);
        pnlViewAllStock.setLayout(pnlViewAllStockLayout);
        pnlViewAllStockLayout.setHorizontalGroup(
            pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                    .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                        .addComponent(btnViewAllStockBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPromptUpdate)))
                .addContainerGap())
        );
        pnlViewAllStockLayout.setVerticalGroup(
            pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewAllStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(pnlViewAllStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAllStockBack)
                    .addComponent(btnPromptUpdate)
                    .addComponent(btnDeleteStock))
                .addContainerGap())
        );

        tpAdminControls.addTab("Manage All Stock", pnlViewAllStock);

        jmAdminApplication.setText("Application");

        jmAdminLogout.setText("Logout");
        jmAdminLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdminLogoutActionPerformed(evt);
            }
        });
        jmAdminApplication.add(jmAdminLogout);
        jmAdminApplication.add(jSeparator1);

        jmAdminClose.setText("Close");
        jmAdminClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdminCloseActionPerformed(evt);
            }
        });
        jmAdminApplication.add(jmAdminClose);

        jmbAdminModule.add(jmAdminApplication);

        jmAccounts.setText("Accounts");

        jmManageRegisteredUsers.setText("Manage Registered Users");
        jmManageRegisteredUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManageRegisteredUsersActionPerformed(evt);
            }
        });
        jmAccounts.add(jmManageRegisteredUsers);

        jmViewRegistrationRequests.setText("View Registration Requests");
        jmViewRegistrationRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmViewRegistrationRequestsActionPerformed(evt);
            }
        });
        jmAccounts.add(jmViewRegistrationRequests);

        jmbAdminModule.add(jmAccounts);

        jMenu2.setText("Stationary");

        jmManageStocks.setText("Manage Stocks");

        jmManageAllStock.setText("Manage All Stock");
        jmManageAllStock.setActionCommand("");
        jmManageAllStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManageAllStockActionPerformed(evt);
            }
        });
        jmManageStocks.add(jmManageAllStock);

        jmInserStock.setText("Insert Stock");
        jmInserStock.setActionCommand("Insert New Stock");
        jmInserStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmInserStockActionPerformed(evt);
            }
        });
        jmManageStocks.add(jmInserStock);

        jMenu2.add(jmManageStocks);

        jmbAdminModule.add(jMenu2);

        setJMenuBar(jmbAdminModule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAdminControls)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAdminControls, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PopulateTableUsers()
    {
        try
        {
            users = new Staff().LoadUsers();

            DefaultTableModel model = (DefaultTableModel) tblViewUsers.getModel();

            for (Staff staffData : users)
            {
                Object[] o = new Object[9];
                o[0] = staffData.getStaffID();
                o[1] = staffData.getStaffName();
                o[2] = staffData.getStaffSurname();
                o[3] = new Campus().GetCampus(staffData.getStaffCampusID()).getCampusName();
                o[4] = new Department().GetDepartment(staffData.getStaffDepartment()).getDepartmentName();
                o[5] = staffData.getStaffCellNo();
                o[6] = staffData.getStaffEmail();
                o[7] = staffData.getStaffUsername();
                o[8] = staffData.getStaffPassword();
                model.addRow(o);
            }

            tblViewUsers.setModel(model);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }

    private void PopulateTableRegister()
    {
        try
        {
            registerStaff = new Staff().LoadRegisterRequests();

            DefaultTableModel model = (DefaultTableModel) tblRegisterRequests.getModel();

            for (Staff staffData : registerStaff)
            {
                Object[] o = new Object[9];
                o[0] = staffData.getRegisterRequestDate();
                o[1] = staffData.getStaffName();
                o[2] = staffData.getStaffSurname();
                o[3] = new Campus().GetCampus(staffData.getStaffCampusID()).getCampusName();
                o[4] = new Department().GetDepartment(staffData.getStaffDepartment()).getDepartmentName();
                o[5] = staffData.getStaffCellNo();
                o[6] = staffData.getStaffEmail();
                o[7] = staffData.getStaffUsername();
                o[8] = staffData.getStaffPassword();
                model.addRow(o);
            }

            tblRegisterRequests.setModel(model);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }

    private void PopulateTableAllStock()
    {
        try
        {
            stationaryStock = new StationaryStock().LoadStationaryStock();

            DefaultTableModel model = (DefaultTableModel) tblAllStock.getModel();

            for (StationaryStock stockData : stationaryStock)
            {
                Object[] o = new Object[9];
                o[0] = stockData.getStationaryStockID();
                o[1] = stockData.getProductName();
                o[2] = new StationaryCategory().GetStationaryCategory(stockData.getStationaryCategoryID()).getName();
                o[3] = stockData.getModel();
                o[4] = stockData.getPrice();
                o[5] = stockData.getQuantity();
                o[6] = stockData.getDateOfEntryUpdate();
                model.addRow(o);
            }

            tblAllStock.setModel(model);
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError(aiob.toString());
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }

    private void jmAdminCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmAdminCloseActionPerformed
    {//GEN-HEADEREND:event_jmAdminCloseActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this application?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jmAdminCloseActionPerformed

    private void jmAdminLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmAdminLogoutActionPerformed
    {//GEN-HEADEREND:event_jmAdminLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            dispose();
            new Thread(new BC_StationaryManagementSystem()).start();
        }
    }//GEN-LAST:event_jmAdminLogoutActionPerformed

    private void jmViewRegistrationRequestsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmViewRegistrationRequestsActionPerformed
    {//GEN-HEADEREND:event_jmViewRegistrationRequestsActionPerformed
        try
        {
            if (!tpAdminControls.getSelectedComponent().equals(tabPanels[1]))
            {
                tpAdminControls.addTab("User Registration Requests", tabPanels[1]);
                tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
                PopulateTableRegister();
            }
        } catch (NullPointerException npe)
        {
            tpAdminControls.addTab("User Registration Requests", tabPanels[1]);
            tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
            PopulateTableRegister();
        }
    }//GEN-LAST:event_jmViewRegistrationRequestsActionPerformed

    private void SelectRowStock()
    {
        try
        {
            for (StationaryStock stock : stationaryStock) {
                if (tblAllStock.getValueAt(tblAllStock.getSelectedRow(), 0).toString().equals(stock.getStationaryStockID()))
                {
                    selectedStock = stock;              
                }
                else
                {
                    Helper.DisplayError("An Error Occoured When Selecting Active Row");
                }
            }
        }
        catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError("Please Select A Row First before Making a selection");
        }   
    }
    private void SelectRowRegister()
    {
        try
        {
            for (Staff staff : registerStaff)
            {
                if (tblRegisterRequests.getValueAt(tblRegisterRequests.getSelectedRow(), 7).toString().equals(staff.getStaffUsername()))
                {
                    selectedStaff = staff;
                } else
                {
                    Helper.DisplayError("An Error Occoured When Selecting Active Row");
                }
            }
        } catch (ArrayIndexOutOfBoundsException aiob)
        {
            Helper.DisplayError("Please Select A Row First before Making a selection");
        }      
    }
    private void jmManageRegisteredUsersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmManageRegisteredUsersActionPerformed
    {//GEN-HEADEREND:event_jmManageRegisteredUsersActionPerformed
        try
        {
            if (!tpAdminControls.getSelectedComponent().equals(tabPanels[0]))
            {
                tpAdminControls.addTab("Manage Staff", tabPanels[0]);
                tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
                PopulateTableUsers();
            }
        } catch (NullPointerException npe)
        {
            tpAdminControls.addTab("Manage Staff", tabPanels[0]);
            tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
            PopulateTableUsers();
        }
    }//GEN-LAST:event_jmManageRegisteredUsersActionPerformed

    private void jmManageAllStockActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmManageAllStockActionPerformed
    {//GEN-HEADEREND:event_jmManageAllStockActionPerformed
        try
        {
            if (!tpAdminControls.getSelectedComponent().equals(tabPanels[2]))
            {
                tpAdminControls.addTab("Manage All Stock", tabPanels[2]);
                tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
                PopulateTableAllStock();
            }
        } catch (NullPointerException npe)
        {
            tpAdminControls.addTab("Manage All Stock", tabPanels[2]);
            tpAdminControls.setSelectedIndex(tpAdminControls.getComponentCount() - 1);
            PopulateTableAllStock();
        }
    }//GEN-LAST:event_jmManageAllStockActionPerformed

    private void jmInserStockActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmInserStockActionPerformed
    {//GEN-HEADEREND:event_jmInserStockActionPerformed
        this.dispose();
        StockDialog sd = new StockDialog(null, true);
        sd.setVisible(true);     
    }//GEN-LAST:event_jmInserStockActionPerformed

    private void btnDeleteStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStockMouseClicked
        try
        {
            SelectRowStock();
            selectedStock.DeleteStockItem();
            stationaryStock.remove(selectedStock);

            DefaultTableModel model = (DefaultTableModel) tblAllStock.getModel();
            model.setRowCount(0);

            PopulateTableRegister();
            JOptionPane.showConfirmDialog(this, "Stock Item Succesfully Updated!", "Update Succesful", JOptionPane.DEFAULT_OPTION);
        }
        catch (NullPointerException npe)
        {
            Helper.DisplayError("There is no data currently available in the table");
        }
    }//GEN-LAST:event_btnDeleteStockMouseClicked

    private void btnPromptUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromptUpdateMouseClicked
        try
        {
            SelectRowStock();
            selectedStock.DeleteStockItem();
            stationaryStock.remove(selectedStock);

            DefaultTableModel model = (DefaultTableModel) tblAllStock.getModel();
            model.setRowCount(0);

            PopulateTableRegister();
            JOptionPane.showConfirmDialog(this, "Stock Item Succesfully Removed!", "Delete Succesful", JOptionPane.DEFAULT_OPTION);
        }
        catch (NullPointerException npe)
        {
            Helper.DisplayError("There is no data currently available in the table");
        }
    }//GEN-LAST:event_btnPromptUpdateMouseClicked

    private void btnViewAllStockBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewAllStockBackMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblAllStock.getModel();
        model.setRowCount(0);
        tpAdminControls.remove(tabPanels[2]);
    }//GEN-LAST:event_btnViewAllStockBackMouseClicked

    private void btnAcceptUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptUserMouseClicked
        try
        {
            selectedStaff.InsertStaff();
            registerStaff.remove(selectedStaff);
            tblRegisterRequests.setModel(new DefaultTableModel());
            PopulateTableRegister();
            JOptionPane.showConfirmDialog(this, "User succesfully Accepted", "Registration Completed", JOptionPane.DEFAULT_OPTION);
        }
        catch (NullPointerException npe)
        {
            Helper.DisplayError("There is no data currently available in the table");
        }
    }//GEN-LAST:event_btnAcceptUserMouseClicked

    private void btnDeleteRegisterUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteRegisterUserMouseClicked
        try
        {
            SelectRowRegister();
            selectedStaff.DeleteRegistry();
            registerStaff.remove(selectedStaff);

            DefaultTableModel model = (DefaultTableModel) tblRegisterRequests.getModel();
            model.setRowCount(0);

            PopulateTableRegister();
            JOptionPane.showConfirmDialog(this, "User succesfully Removed", "Registration Completed", JOptionPane.DEFAULT_OPTION);
        }
        catch (NullPointerException npe)
        {
            Helper.DisplayError("There is no data currently available in the table");
        }
    }//GEN-LAST:event_btnDeleteRegisterUserMouseClicked

    private void btnRegisterUserBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterUserBackMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblRegisterRequests.getModel();
        model.setRowCount(0);
        tpAdminControls.remove(tabPanels[1]);
    }//GEN-LAST:event_btnRegisterUserBackMouseClicked

    private void btnViewUsersBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewUsersBackMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblViewUsers.getModel();
        model.setRowCount(0);
        tpAdminControls.remove(tabPanels[0]);
    }//GEN-LAST:event_btnViewUsersBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JAdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JAdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JAdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JAdminModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new JAdminModule().setVisible(true);

                tblRegisterRequests.getModel().addTableModelListener(new TableModelListener()
                {
                    @Override
                    public void tableChanged(TableModelEvent e)
                    {
                        for (Staff staff : registerStaff)
                        {
                            if (tblRegisterRequests.getValueAt(e.getFirstRow(), 7).toString().equals(staff.getStaffUsername()))
                            {
                                selectedStaff = staff;
                                System.out.println(selectedStaff.toString());
                            }
                        }
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptUser;
    private javax.swing.JButton btnDeleteRegisterUser;
    private javax.swing.JButton btnDeleteStock;
    private javax.swing.JButton btnPromptUpdate;
    private javax.swing.JButton btnRegisterUserBack;
    private javax.swing.JButton btnViewAllStockBack;
    private javax.swing.JButton btnViewUsersBack;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmAccounts;
    private javax.swing.JMenu jmAdminApplication;
    private javax.swing.JMenuItem jmAdminClose;
    private javax.swing.JMenuItem jmAdminLogout;
    private javax.swing.JMenuItem jmInserStock;
    private javax.swing.JMenuItem jmManageAllStock;
    private javax.swing.JMenuItem jmManageRegisteredUsers;
    private javax.swing.JMenu jmManageStocks;
    private javax.swing.JMenuItem jmViewRegistrationRequests;
    private javax.swing.JMenuBar jmbAdminModule;
    private javax.swing.JPanel pnlManageStaff;
    private javax.swing.JPanel pnlUserRegistrationRequests;
    private javax.swing.JPanel pnlViewAllStock;
    private javax.swing.JTable tblAllStock;
    private javax.swing.JTable tblRegisterRequests;
    private javax.swing.JTable tblViewUsers;
    private javax.swing.JTabbedPane tpAdminControls;
    // End of variables declaration//GEN-END:variables
}
