/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationModule.JLayourForms;

import ApplicationHelper.Helper;
import Authentication.AuthenticationSettings;
import BusinessModule.Staff;
import PresentationModule.BC_StationaryManagementSystem;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Neil
 */
public class JStaffModule extends javax.swing.JFrame
{

    public JStaffModule()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jmbStaffModule = new javax.swing.JMenuBar();
        jmStaffAccount = new javax.swing.JMenu();
        jmStaffMyAccount = new javax.swing.JMenuItem();
        jmStaffLogout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmStaffModuleClose = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmStaffOrders = new javax.swing.JMenu();
        jmStaffOrdersPending = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmStaffStationary = new javax.swing.JMenu();
        jmStaffViewStationary = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmStaffAccount.setText("Account");

        jmStaffMyAccount.setText("My Account");
        jmStaffMyAccount.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmStaffMyAccountActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffMyAccount);

        jmStaffLogout.setText("Logout");
        jmStaffLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmStaffLogoutActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffLogout);
        jmStaffAccount.add(jSeparator2);

        jmStaffModuleClose.setText("Close");
        jmStaffModuleClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jmStaffModuleCloseActionPerformed(evt);
            }
        });
        jmStaffAccount.add(jmStaffModuleClose);
        jmStaffAccount.add(jSeparator1);

        jmbStaffModule.add(jmStaffAccount);

        jmStaffOrders.setText("Orders");

        jmStaffOrdersPending.setText("My Pending Orders");
        jmStaffOrders.add(jmStaffOrdersPending);

        jMenuItem1.setText("My Orders");
        jmStaffOrders.add(jMenuItem1);

        jmbStaffModule.add(jmStaffOrders);

        jmStaffStationary.setText("Stationary");

        jmStaffViewStationary.setText("View Stationary");
        jmStaffViewStationary.setToolTipText("");
        jmStaffStationary.add(jmStaffViewStationary);

        jmbStaffModule.add(jmStaffStationary);

        setJMenuBar(jmbStaffModule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmStaffMyAccountActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffMyAccountActionPerformed
    {//GEN-HEADEREND:event_jmStaffMyAccountActionPerformed
        try
        {
            this.setVisible(false);
            JUserAccount jua = new JUserAccount();
            jua.setVisible(true);
        }
        catch(NullPointerException npe)
        {
            Helper.DisplayError(npe.toString());
        }
    }//GEN-LAST:event_jmStaffMyAccountActionPerformed

    private void jmStaffLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffLogoutActionPerformed
    {//GEN-HEADEREND:event_jmStaffLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            dispose();
            new Thread(new BC_StationaryManagementSystem()).start();
        }   
    }//GEN-LAST:event_jmStaffLogoutActionPerformed

    private void jmStaffModuleCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jmStaffModuleCloseActionPerformed
    {//GEN-HEADEREND:event_jmStaffModuleCloseActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this application?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jmStaffModuleCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JStaffModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JStaffModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jmStaffAccount;
    private javax.swing.JMenuItem jmStaffLogout;
    private javax.swing.JMenuItem jmStaffModuleClose;
    private javax.swing.JMenuItem jmStaffMyAccount;
    private javax.swing.JMenu jmStaffOrders;
    private javax.swing.JMenuItem jmStaffOrdersPending;
    private javax.swing.JMenu jmStaffStationary;
    private javax.swing.JMenuItem jmStaffViewStationary;
    private javax.swing.JMenuBar jmbStaffModule;
    // End of variables declaration//GEN-END:variables
}
