/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationModule.JLayourForms;

import ApplicationHelper.Helper;
import Authentication.ActiveAccess;
import BusinessModule.StationaryCategory;
import BusinessModule.StationaryStock;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author monteh
 */
public class StockDialog extends javax.swing.JDialog
{

    private List<StationaryCategory> categories = new ArrayList<>();

    /**
     * Creates new form StockDialog
     *
     * @param parent
     * @param modal
     */
    public StockDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        LoadBoxCategory();
        ResetInsertForm();
    }

    private void LoadBoxCategory()
    {
        try
        {
            categories = new StationaryCategory().ReadStationaryCategory();

            for (StationaryCategory categoryData : categories)
            {
                cmbInsertCatgory.addItem(categoryData.getName());
            }

            cmbInsertCatgory.setSelectedIndex(0);
        } catch (NullPointerException npe)
        {
            Helper.DisplayError(npe.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmitStock = new javax.swing.JButton();
        btnBackStock = new javax.swing.JButton();
        btnClearStock = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInsertProductName = new javax.swing.JTextField();
        cmbInsertCatgory = new javax.swing.JComboBox<>();
        txtInsertModel = new javax.swing.JTextField();
        spnInsertQuantity = new javax.swing.JSpinner();
        txtInsertPrice = new javax.swing.JTextField();
        btnCloseStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stationary Stock Form");

        btnSubmitStock.setText("Submit");
        btnSubmitStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitStockMouseClicked(evt);
            }
        });

        btnBackStock.setText("Back");
        btnBackStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackStockMouseClicked(evt);
            }
        });

        btnClearStock.setText("Clear");
        btnClearStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearStockMouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock Information"));

        jLabel1.setText("Product Name:");

        jLabel2.setText("Category Name:");

        jLabel3.setText("Model:");

        jLabel4.setText("Price:");

        jLabel5.setText("Quantity:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbInsertCatgory, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtInsertPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtInsertModel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spnInsertQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txtInsertProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtInsertProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(cmbInsertCatgory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsertModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsertPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnInsertQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(65, 65, 65))
        );

        btnCloseStock.setText("Close");
        btnCloseStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmitStock)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitStock)
                    .addComponent(btnBackStock)
                    .addComponent(btnClearStock)
                    .addComponent(btnCloseStock))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackStockMouseClicked
        dispose();
    }//GEN-LAST:event_btnBackStockMouseClicked

    private void btnCloseStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseStockMouseClicked
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to close this application?", "User Confirmation", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseStockMouseClicked

    private void btnClearStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearStockMouseClicked
        ResetInsertForm();
    }//GEN-LAST:event_btnClearStockMouseClicked

    private void btnSubmitStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitStockMouseClicked
        Validation val = new Validation();
        boolean validInput = false;
        String productName, category, model, price, quantity;
        int categoryID = 0;

        productName = txtInsertProductName.getText();
        category = cmbInsertCatgory.getSelectedItem().toString();
        model = txtInsertModel.getText();
        price = txtInsertPrice.getText();
        quantity = spnInsertQuantity.getValue().toString();

        try
        {
            validInput = val.ValidateStockEntry(productName, category, model, price, quantity);

            if (validInput)
            {
                for (StationaryCategory categoryData : categories)
                {
                    if (categoryData.getName().equals(category))
                    {
                        categoryID = categoryData.getStationaryCategoryID();
                    }
                }

                if (categoryID != 0)
                {                
                    if (ActiveAccess.getCurrentStock() == null)
                    {
                        StationaryStock statStock = new StationaryStock(productName, categoryID, model, Double.parseDouble(price), Integer.parseInt(quantity));
                        statStock.InsertStationaryStock();
                        JOptionPane.showConfirmDialog(this, "Stock Entry Has Been Entered Succesfully", "Entry Recieved", JOptionPane.DEFAULT_OPTION);
                        dispose();
                    }
                    else
                    {
                        StationaryStock statStock = new StationaryStock(ActiveAccess.getCurrentStock().getStationaryStockID(), productName, categoryID, model, Double.parseDouble(price), Integer.parseInt(quantity));
                        statStock.UpdateStockEntry();
                        ActiveAccess.setCurrentStock(null);
                        JOptionPane.showConfirmDialog(this, "Stock Item Succesfully Updated!", "Update Succesful", JOptionPane.DEFAULT_OPTION);
                        dispose();
                    }          
                } else
                {
                    throw new Exception("Error in ID set for field!");
                }
            } else
            {
                ResetInsertForm();
            }
        } catch (Exception ex)
        {
            Helper.DisplayError(ex.toString());
        }
    }//GEN-LAST:event_btnSubmitStockMouseClicked

    private void ResetInsertForm()
    {
        if (ActiveAccess.getCurrentStock() == null)
        {
            txtInsertProductName.setText("");
            txtInsertModel.setText("");
            txtInsertPrice.setText("");
            cmbInsertCatgory.setSelectedIndex(0);
            spnInsertQuantity.setValue(0);
        } else
        {
            txtInsertProductName.setText(ActiveAccess.getCurrentStock().getProductName());
            txtInsertModel.setText(ActiveAccess.getCurrentStock().getModel());
            txtInsertPrice.setText(String.valueOf(ActiveAccess.getCurrentStock().getPrice()));
            cmbInsertCatgory.setSelectedIndex(categories.indexOf(ActiveAccess.getCurrentStock().getStationaryCategoryID()));
            spnInsertQuantity.setValue(ActiveAccess.getCurrentStock().getQuantity());
            
            for (StationaryCategory category : categories)
            {
                if(category.getStationaryCategoryID() == ActiveAccess.getCurrentStock().getStationaryCategoryID())
                {
                    cmbInsertCatgory.setSelectedItem(category.getName());
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(StockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(StockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(StockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(StockDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                StockDialog dialog = new StockDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackStock;
    private javax.swing.JButton btnClearStock;
    private javax.swing.JButton btnCloseStock;
    private javax.swing.JButton btnSubmitStock;
    private javax.swing.JComboBox<String> cmbInsertCatgory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spnInsertQuantity;
    private javax.swing.JTextField txtInsertModel;
    private javax.swing.JTextField txtInsertPrice;
    private javax.swing.JTextField txtInsertProductName;
    // End of variables declaration//GEN-END:variables
}
